<template>
  <div class="darkbox-container">
    <div class="darkbox-box" ref="db">
      <i class="fa fa-times-circle close" aria-hidden="true" @click="closeDarkbox"></i>
      <div class="img-container" ref="ic" @click="closeDarkbox">

      </div>
    </div>
    <img class="darkbox" :src="'/static/images/thumbs/galeria01.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria02.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria03.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria04.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria05.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria06.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria07.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria08.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria010.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria011.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria012.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria013.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria014.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria015.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria016.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria017.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria018.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria019.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria020.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria021.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria022.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria024.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria025.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria026.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria027.jpg'" alt="prodentica gabinet">
    <img class="darkbox" :src="'/static/images/thumbs/galeria028.jpg'" alt="prodentica gabinet">



  </div>
</template>

<script>
export default {
  name: 'app',
  data () {
    return {
      thumbSize: 330,
      imgSize: 900,
      images: {
        one: 'galeria01.jpg'
      }
    }
  },
  methods: {
    openDarkbox() {
      let darkbox = document.querySelector('.darkbox-box');
      let imgContainer = document.querySelector('.img-container');
      this.$refs.db.style.display = 'block';
      //imgContainer.style.width = `${this.imgSize}px`;
      imgContainer.classList.add('fade-in');

    },
    closeDarkbox() {
      this.$refs.ic.firstChild.remove();
      this.$refs.db.style.display = 'none';
    },
    getImages() {
      let imgs = document.querySelectorAll('.darkbox');
      imgs.forEach((el) => {
        //el.width = this.thumbSize;
        el.addEventListener('click', (e) => {
          //open darbox
        this.openDarkbox();
        let sourceImage = document.createElement('img');
        // sourceImage.src = e.target.src;
        let filename = e.target.src.replace(/^.*[\\\/]/, '');
        // let filename2 = filename.replace(/.jpg/, '-big.jpg');
        console.log(filename);
        sourceImage.src = '/static/images/' + filename;

        sourceImage.style.width = '600px';
        this.$refs.ic.appendChild(sourceImage);
        });
      });
    }
  },
  mounted() {
    this.getImages();
  }
}
</script>

<style>

.darkbox {
  cursor: pointer;
}

.img-container {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 900px;
  text-align: center;
}

.darkbox-container img {
  width: 33%;
}

.img-container img {
  border: 15px solid black;
  cursor: pointer;
  width: 33%;
}

.darkbox-box {
  top: 0;
  left: 0;
  position: fixed;
  display: none;
  background-color: rgba(255, 255, 255, 0.7);
  width: 100vw;
  height: 100vh;
  z-index: 100;
}

.darkbox-box i {
  font-size: 2em;
  cursor: pointer;
}

.fade-in {
	-webkit-animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2018-3-19 9:1:59
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

@media screen and (max-width: 599px) {
  .darkbox-container img {
    width: 100%;
  }
  .img-container, .img-container img {
    width: 90%;
  }

}

@media screen and (min-width: 600px) and (max-width: 999px) {

  .darkbox-container img {
    width: 49.5%;
  }

  .img-container, .img-container img {
    width: 90%;
  }

}


</style>
