<template>
  <div class="darkbox-container">
    <div class="darkbox-box" ref="db">
      <i class="fa fa-times-circle close" aria-hidden="true" @click="closeDarkbox"></i>
      <div class="img-container" ref="ic" @click="closeDarkbox">

      </div>
    </div>
    
    <img class="darkbox" src="./assets/images/placeholder.jpg" alt="asa">
    <img class="darkbox" src="./assets/images/placeholder2.jpg" alt="asa">
    <img class="darkbox" src="./assets/images/placeholder3.jpg" alt="asa">
    <img class="darkbox" src="./assets/images/placeholder4.jpg" alt="asa">
    <img class="darkbox" src="./assets/images/placeholder5.jpg" alt="asa">
    <img class="darkbox" src="./assets/images/placeholder6.jpg" alt="asa">
    <img class="darkbox" src="./assets/images/placeholder7.jpg" alt="asa">
    <img class="darkbox" src="./assets/images/placeholder8.jpg" alt="asa">
    <img class="darkbox" src="./assets/images/placeholder9.jpg" alt="asa">

  </div>
</template>

<script>
export default {
  name: 'app',
  data () {
    return {
      thumbSize: 330,
      imgSize: 900,
    }
  },
  methods: {
    openDarkbox() {
      let darkbox = document.querySelector('.darkbox-box');
      let imgContainer = document.querySelector('.img-container');
      this.$refs.db.style.display = 'block';
      imgContainer.style.width = `${this.imgSize}px`;
      imgContainer.classList.add('fade-in');

    },
    closeDarkbox() {
      this.$refs.ic.firstChild.remove();
      this.$refs.db.style.display = 'none';
    },
    getImages() {
      let imgs = document.querySelectorAll('.darkbox');
      imgs.forEach((el) => {
        el.width = this.thumbSize;
        el.addEventListener('click', (e) => {
          //open darbox
        this.openDarkbox();
        let sourceImage = document.createElement('img');
        sourceImage.src = e.target.src;
        sourceImage.style.width = '100%';
        this.$refs.ic.appendChild(sourceImage);
        });
      });
    }
  },
  mounted() {
    this.getImages();
  }
}
</script>

<style>

.darkbox {
  cursor: pointer;
}

.img-container {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.img-container img {
  border: 15px solid black;
  cursor: pointer;
}

.darkbox-box {
  top: 0;
  left: 0;
  position: fixed;
  display: none;
  background-color: rgba(255, 255, 255, 0.7);
  width: 100vw;
  height: 100vh;
  z-index: 99;
}

.darkbox-box i {
  font-size: 2em;
  cursor: pointer;
}

.fade-in {
	-webkit-animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2018-3-19 9:1:59
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}




</style>
